namespace: pluebker-test

configmap:
  name: sudokuconfigmap
  data:
    BACKEND_SERVER: "sudoku-backend:3000"

backend:
  appName: sudoku-backend
  image:
   name: ghcr.io/ptrk25/sudoku-backend
   tag: latest

frontend:
  appName: sudoku-frontend
  image:
   name: ghcr.io/ptrk25/sudoku-frontend
   tag: latest