apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.containers.backend.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.containers.backend.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.containers.backend.appName }}
  ports:
    - port: {{ .Values.containers.backend.ports.external }}
      targetPort: {{ .Values.containers.backend.ports.internal }}
      name: {{ .Values.containers.backend.appName }}
