apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.containers.frontend.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.containers.frontend.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.containers.frontend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.containers.frontend.appName }}
    spec:
      containers:
      - name: {{ .Values.containers.frontend.appName }}
        image: "{{ .Values.containers.frontend.image.name }}:{{ .Values.containers.frontend.image.tag}}"
        imagePullPolicy: {{ .Values.containers.frontend.image.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        ports:
          - containerPort: {{ .Values.containers.frontend.ports.internal }}