apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appName }}
    spec:
      containers:
      - name: {{ .Values.frontend.appName }}
        image: {{ printf "%v:%v" .Values.frontend.image.name (tpl .Values.frontend.image.tag .) }}
        imagePullPolicy: {{ .Values.frontend.image.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        ports:
          - containerPort: {{ .Values.frontend.ports.internal }}