configmap:
  name: sudokuconfigmap
  data:
    BACKEND_SERVER: "{{ .Values.backend.appName }}"
    ENVIRONMENT: prod

backend:
  appName: sudoku-backend
  image:
    name: ghcr.io/ptrk25/sudoku-backend
    tag: v0.1.0
    imagePullPolicy: IfNotPresent
  ports:
    internal: 3000
    external: 3000

frontend:
  appName: sudoku-frontend
  image:
    name: ghcr.io/ptrk25/sudoku-frontend
    tag: v0.2.0
    imagePullPolicy: IfNotPresent
  ports:
    internal: 3000
    external: 3000

route:
  enable: true
  name: sudoku-route
  host: sudoku-test.apps.ccnap.bpe.local