namespace: pluebker-test

configmap:
  name: sudokuconfigmap
  data:
    BACKEND_SERVER: "{{ .Values.backend.appName }}"
    ENVIRONMENT: prod

backend:
  appName: sudoku-backend
  image:
    name: ghcr.io/ptrk25/sudoku-backend
    imagePullPolicy: IfNotPresent
  ports:
    internal: 3000
    external: 3000

frontend:
  appName: sudoku-frontend
  image:
    name: ghcr.io/ptrk25/sudoku-frontend
    imagePullPolicy: IfNotPresent
  ports:
    internal: 3000
    external: 3000