apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backend.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.backend.appName }}
  ports:
    - port: 3000
      targetPort: 3000
      name: {{ .Values.backend.appName }}
