apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.appName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.frontend.appName }}
  ports:
    - port: 3000
      targetPort: 3000
      name: {{ .Values.frontend.appName }}